apiVersion: argoproj.io/v1alpha1
kind: Workflow

metadata:
  generateName: jupyterhub-uat-release-
  namespace: argo

spec:

  workflowTemplateRef:
    name: jupyterhub-uat-release

  arguments:
    parameters:

      - name: application
        value: jupyterhub

      - name: environment
        value: uat

      - name: imageTag
        value: "1.30"

      - name: releaseBranch
        value: release-uat

      - name: overlayPath
        value: platform/overlays/uat/jupyterhub

      - name: releaseRepo
        value: https://github.com/vinaynakirikanti151-crypto/Gitops.git