apiVersion: apps/v1
kind: Deployment

metadata:
  name: jupyterhub-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: jupyterhub-demo

  template:
    metadata:
      labels:
        app: jupyterhub-demo

    spec:
      containers:
        - name: jupyterhub-demo
          image: nginx:1.27

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 200m
              memory: 128Mi