apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: jupyterhub-uat
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vinaynakirikanti151-crypto/Gitops.git
    targetRevision: release-uat
    path: platform/overlays/uat/jupyterhub

  destination:
    server: https://kubernetes.default.svc
    namespace: jupyterhub-uat

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true